### ISSUE TITLE
missing tables in A2

### ISSUE THREAD

**Issue by arastella625** [rhodyprog4ds/BrownSpring23#2]
Here you state:
1. save it to a local csv using the short name you provided for the dataset as the file name, without writing the index column to the file.

2.record attributes about the dataset as in the table below in a list of lists or dictionary
- You don't have a table below to follow any reference to. How many attributes are we recording?

3.Use that to create a DataFrame with columns that match the rows of the following table.
-You do not have a table to reference this step to. What do you mean columns that match the rows of the following table?

**Comment by brownsarahm** [comment]
In the future use a descriptive name. 
The tables are visible here: https://github.com/rhodyprog4ds/BrownSpring23/blob/main/assignments/02-python-access.md 

I'm not sure why they're not showing the other way.
