### ISSUE TITLE
Issue on page /assignments/02-python-access.html

### ISSUE THREAD

**Issue by VinaiPhomsouvannady** [rhodyprog4ds/BrownSpring23#5]
Assignment 2 is not updated as there are no submission instructions and it seems to be missing some clarification/instructions.

**Comment by brownsarahm** [comment]
The submission is there. 

I'm not sure why the tables are missing, but you can see them here: https://github.com/rhodyprog4ds/BrownSpring23/blob/main/assignments/02-python-access.md
