### ISSUE TITLE
Submission Placement

### ISSUE THREAD

**Issue by arastella625** [rhodyprog4ds/BrownSpring23#6]
I understand that you have answered the question and directed us to the website, however under submission it still says "This is TBA instructions will be here on Thursday". 

Yet, the assignment is due tonight. Is this still supposed to be correct?

**Comment by brownsarahm** [comment]
There's a repo link under tasks.  GitHub is having an issue so I cannot delete that sentence.

**Comment by brownsarahm** [comment]
leave this issue open until the website is actually fixed

**Comment by brownsarahm** [comment]
this was fixed.
